### ISSUE TITLE
连接正式MQ 服务器，不可识别的包，连接失败

### ISSUE THREAD

**Issue by thisfeng** [Rairmmd/AndMqtt#1]
我在自己本地搭建的一个MQ服务器，和同事的本地MQ服务器都可以连接上，但是唯独线上的时候，总是连接失败。我还没找到原因。不知作者是否有遇到过

**Comment by Reathin** [comment]
这个问题我暂时没遇到过   公司目前也用的没出现问题

**Comment by thisfeng** [comment]
使用後台小哥配置過的 Netty，成功踩了多個坑後對接上了。Demo很不錯 還是學習 thanks

**Comment by Reathin** [comment]
不客气  (*^▽^*)
